# Generated by Django 3.2.7 on 2022-12-11 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username', models.CharField(blank=True, max_length=100000)),
                ('long', models.DecimalField(decimal_places=20, max_digits=40)),
                ('lang', models.DecimalField(decimal_places=20, max_digits=40)),
                ('adress', models.TextField()),
                ('localty', models.CharField(blank=True, max_length=100000)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
